/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class jni_test_JniTestEntry */

#ifndef _Included_jni_test_JniTestEntry
#define _Included_jni_test_JniTestEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_test_JniTestEntry
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1test_JniTestEntry_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     jni_test_JniTestEntry
 * Method:    nativeMethodAccessJavaField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_1test_JniTestEntry_nativeMethodAccessJavaField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
